name: Build Project

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'

    - name: Build project
      run: |
        echo "Building project..."
        ./scripts/make.sh build
